---
- name: Cisco SW and Router Backup
  hosts : HST_SSH_SW,HST_SSH_RT
  connection: network_cli
  tasks:

    - name: Get timestamp from the system
      shell: "date +%d-%m-%Y%-H-%M-%S"
      register: tstamp
    - debug: var=tstamp.stdout_lines

    - name: Set variables
      set_fact:
       cur_date: "{{ tstamp.stdout[0:10]}}"
       cur_time: "{{ tstamp.stdout[10:]}}"

    - name: TASK1 - GET VERSION/INVENTORY/INTERFACE UPTIME/BACKUP
      ios_command:
        commands:
           - terminal length 0
           - show version
           - show inventory
           - show interfaces | i Last|line
           - show run
      register: cli_result

    - name: Task3  Create Outputs/ Folder
      file:
        path: "outputs"
        state: directory
      run_once: true

    - name: save output
      blockinfile:
          create: yes
          dest: "outputs/{{ inventory_hostname }}-{{cur_date}}-{{cur_time}}.txt"
          marker: "#{mark} BLOCK GROUP 1"
          block: |
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            #show version
            {{ cli_result.stdout[1] }}
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            #show inventory
            {{ cli_result.stdout[2] }}
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            #show interface | i last|Line
            {{ cli_result.stdout[3] }}
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            #show run
            {{ cli_result.stdout[4] }}

- name: Get device information
  hosts: HST_JUNOS_FW
  roles:
    - Juniper.junos
  connection: local
  gather_facts: no
  tasks:
    - name: Get timestamp from the system
      shell: "date +%d-%m-%Y%-H-%M-%S"
      register: tstamp
    - debug: var=tstamp.stdout_lines

    - name: Set variables
      set_fact:
       cur_date: "{{ tstamp.stdout[0:10]}}"
       cur_time: "{{ tstamp.stdout[10:]}}"
    - name: Infra FW
      juniper_junos_command:
        commands:
          - "show version"
          - "show configuration"
        formats:
          - "text"
        dest: "outputs/{{ inventory_hostname }}-{{cur_date}}-{{cur_time}}.txt"
